### ISSUE TITLE
Why is JLD2 a dependency?

### ISSUE THREAD

**Issue by Datseris** [rveltz/BifurcationKit.jl#22]
I just got an upgrade conficlt because of an old version of JLD2 and I thought "Where does it come from?" because I've never installed JLD2. Turns out it was coming from here.

It made me wonder, why would such a front-end package be a dependency here?

**Comment by rveltz** [comment]
Because you can use it to save the branch while being computed. For example, in memory limited (GPU...) you cannot keep the branch with all eigenvectors in RAM whereas this info is needed to compute bifurcations. Hence, I propose saving this info on the disk every once in a while. This is set by `ContinuationPar.saveToFile`.

**Comment by Datseris** [comment]
Yeap, have a look: https://discourse.julialang.org/t/ann-jld2-v0-2-0/45843

You can also use CompatHelper.jl to become aware of bound changes.
